- name: Docker volumes creation
  docker_volume:
    name: "allspark_portainer_data"

- name: Setup Portainer as infra service
  docker_container:
    name: portainer
    image: "{{ allspark_portainer.image }}"
    volumes:
      - "allspark_portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --no-auth --no-analytics --host unix:///var/run/docker.sock
    networks:
      - name: allspark
    labels:
      "traefik.backend": "portainer"
      "traefik.frontend.rule": "Host:infra.{{ allspark_root_domain }}"
      "traefik.enable": "true"
    restart_policy: always

- name: Docker volumes creation
  docker_volume:
    name: "allspark_{{ item }}"
  with_items:
    - rocketchat_data
    - rocketchat_avatars
  when: allspark_rocketchat.enabled

- name: Setup MongoDB chat service database
  docker_container:
    name: rocketchat_database
    image: "{{ allspark_rocketchat.database_image }}"
    state: "{{ allspark_rocketchat.enabled and 'started' or 'absent'}}"
    networks:
      - name: allspark
    volumes:
      - "allspark_rocketchat_data:/data/db"
    restart_policy: always

- name: Setup RocketChat service
  docker_container:
    name: rocketchat
    image: "{{ allspark_rocketchat.image }}"
    state: "{{ allspark_rocketchat.enabled and 'started' or 'absent'}}"
    env:
      MONGO_URL: mongodb://rocketchat_database/rocketchat
      ROOT_URL: "http://chat.{{ allspark_root_domain }}"
    volumes:
      - "allspark_rocketchat_avatars:/app/uploads"
    networks:
      - name: allspark
    labels:
      "traefik.backend": "rocketchat"
      "traefik.frontend.rule": "Host:chat.{{ allspark_root_domain }}"
      "traefik.enable": "true"
    restart_policy: always
